/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { WalletUser, TransactionRecord } from '../types/factory';

export interface TransferRequest {
  idempotencyKey: string;
  senderId: string;
  recipientId: string;
  amountPaise: number;
  simulateMidTxFailure?: boolean;
}

export interface TransferResult {
  success: boolean;
  transaction?: TransactionRecord;
  error?: string;
  systemMoneyBefore: number;
  systemMoneyAfter: number;
  isDuplicate?: boolean;
  isDoubleSpendBug?: boolean;
}

export class WalletEngine {
  private users: Map<string, WalletUser> = new Map();
  private ledger: TransactionRecord[] = [];
  private idempotencyStore: Map<string, TransactionRecord> = new Map();
  private isPatched: boolean = false;
  // Concurrency mutex lock queues for repaired mode
  private walletLocks: Map<string, Promise<void>> = new Map();

  constructor() {
    this.reset();
  }

  public reset(usePatched: boolean = false): void {
    this.isPatched = usePatched;
    this.users.clear();
    this.ledger = [];
    this.idempotencyStore.clear();
    this.walletLocks.clear();

    const initialUsers: WalletUser[] = [
      { id: 'usr_alice', name: 'Alice', email: 'alice@pocketforge.local', balancePaise: 1000000, initialBalancePaise: 1000000 }, // ₹10,000.00
      { id: 'usr_bob', name: 'Bob', email: 'bob@pocketforge.local', balancePaise: 500000, initialBalancePaise: 500000 },         // ₹5,000.00
      { id: 'usr_charlie', name: 'Charlie', email: 'charlie@pocketforge.local', balancePaise: 250000, initialBalancePaise: 250000 }, // ₹2,500.00
      { id: 'usr_david', name: 'David', email: 'david@pocketforge.local', balancePaise: 100000, initialBalancePaise: 100000 },     // ₹1,000.00
    ];

    for (const u of initialUsers) {
      this.users.set(u.id, { ...u });
    }
  }

  public setPatchedMode(patched: boolean): void {
    this.isPatched = patched;
  }

  public getIsPatched(): boolean {
    return this.isPatched;
  }

  public getUsers(): WalletUser[] {
    return Array.from(this.users.values()).map(u => ({ ...u }));
  }

  public getUser(id: string): WalletUser | undefined {
    const u = this.users.get(id);
    return u ? { ...u } : undefined;
  }

  public getLedger(): TransactionRecord[] {
    return [...this.ledger];
  }

  public getTotalSystemMoney(): number {
    let total = 0;
    for (const u of this.users.values()) {
      total += u.balancePaise;
    }
    return total;
  }

  /**
   * Acquire async mutex lock for a specific wallet ID (only active in patched mode)
   */
  private async acquireLock(walletId: string): Promise<() => void> {
    while (this.walletLocks.has(walletId)) {
      await this.walletLocks.get(walletId);
    }
    let resolver: () => void = () => {};
    const promise = new Promise<void>((resolve) => {
      resolver = resolve;
    });
    this.walletLocks.set(walletId, promise);
    return () => {
      this.walletLocks.delete(walletId);
      resolver();
    };
  }

  /**
   * Core transfer operation
   */
  public async executeTransfer(req: TransferRequest): Promise<TransferResult> {
    const systemMoneyBefore = this.getTotalSystemMoney();

    // 1. Validate integer paise requirement (strict integer money check)
    if (!Number.isInteger(req.amountPaise) || req.amountPaise <= 0) {
      return {
        success: false,
        error: 'INVALID_AMOUNT: Amount must be a positive integer in minor units (paise).',
        systemMoneyBefore,
        systemMoneyAfter: this.getTotalSystemMoney(),
      };
    }

    if (req.senderId === req.recipientId) {
      return {
        success: false,
        error: 'SELF_TRANSFER_PROHIBITED: Sender and recipient must be distinct wallets.',
        systemMoneyBefore,
        systemMoneyAfter: this.getTotalSystemMoney(),
      };
    }

    // 2. Check Idempotency Store
    if (this.isPatched) {
      const existing = this.idempotencyStore.get(req.idempotencyKey);
      if (existing) {
        return {
          success: existing.status === 'COMMITTED',
          transaction: existing,
          isDuplicate: true,
          error: existing.status !== 'COMMITTED' ? 'Original request previously failed' : undefined,
          systemMoneyBefore,
          systemMoneyAfter: this.getTotalSystemMoney(),
        };
      }
    }

    // Branching: Patched vs Vulnerable
    if (this.isPatched) {
      return this.executePatchedTransfer(req, systemMoneyBefore);
    } else {
      return this.executeVulnerableTransfer(req, systemMoneyBefore);
    }
  }

  /**
   * Naive / Vulnerable Implementation (Generated by Builder before adversarial testing)
   * Contains two critical flaws:
   * 1. No atomic lock / checks balance then yields to event loop before debiting, allowing double-spend race condition.
   * 2. No idempotency check, allowing duplicate retry storms.
   */
  private async executeVulnerableTransfer(req: TransferRequest, systemMoneyBefore: number): Promise<TransferResult> {
    const sender = this.users.get(req.senderId);
    const recipient = this.users.get(req.recipientId);

    if (!sender || !recipient) {
      return {
        success: false,
        error: 'WALLET_NOT_FOUND',
        systemMoneyBefore,
        systemMoneyAfter: this.getTotalSystemMoney(),
      };
    }

    // Check balance
    if (sender.balancePaise < req.amountPaise) {
      return {
        success: false,
        error: `INSUFFICIENT_FUNDS: Available ${sender.balancePaise} paise, requested ${req.amountPaise} paise.`,
        systemMoneyBefore,
        systemMoneyAfter: this.getTotalSystemMoney(),
      };
    }

    // VULNERABILITY SIMULATION:
    // Yielding to event loop simulates async database read-then-write latency.
    // In this window, another concurrent request can read the stale balance!
    await new Promise(resolve => setTimeout(resolve, 20));

    // Mid-tx failure simulation
    if (req.simulateMidTxFailure) {
      // Flaw: Debit happens but crash occurs before credit, and no rollback mechanism exists!
      sender.balancePaise -= req.amountPaise;
      const tx: TransactionRecord = {
        id: `tx_vuln_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
        idempotencyKey: req.idempotencyKey,
        senderId: sender.id,
        senderName: sender.name,
        recipientId: recipient.id,
        recipientName: recipient.name,
        amountPaise: req.amountPaise,
        status: 'ROLLED_BACK',
        timestamp: new Date().toISOString(),
        systemMoneyChecksumBefore: systemMoneyBefore,
        systemMoneyChecksumAfter: this.getTotalSystemMoney(),
        enginePhase: 'vulnerable',
        reasonNote: 'UNHANDLED_CRASH: Money debited from sender but credit failed! Invariant violated.',
      };
      this.ledger.unshift(tx);
      return {
        success: false,
        transaction: tx,
        error: 'CRASH_WITHOUT_ROLLBACK: System money destroyed!',
        systemMoneyBefore,
        systemMoneyAfter: this.getTotalSystemMoney(),
      };
    }

    // Now debit and credit
    sender.balancePaise -= req.amountPaise;
    recipient.balancePaise += req.amountPaise;

    const isDoubleSpend = sender.balancePaise < 0;

    const tx: TransactionRecord = {
      id: `tx_vuln_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      idempotencyKey: req.idempotencyKey,
      senderId: sender.id,
      senderName: sender.name,
      recipientId: recipient.id,
      recipientName: recipient.name,
      amountPaise: req.amountPaise,
      status: isDoubleSpend ? 'VULNERABILITY_DOUBLE_SPENT' : 'COMMITTED',
      timestamp: new Date().toISOString(),
      systemMoneyChecksumBefore: systemMoneyBefore,
      systemMoneyChecksumAfter: this.getTotalSystemMoney(),
      enginePhase: 'vulnerable',
      reasonNote: isDoubleSpend ? 'RACE CONDITION EXPLOITED: Balance became negative!' : undefined,
    };

    this.ledger.unshift(tx);

    return {
      success: true,
      transaction: tx,
      isDoubleSpendBug: isDoubleSpend,
      systemMoneyBefore,
      systemMoneyAfter: this.getTotalSystemMoney(),
    };
  }

  /**
   * Hardened / Repaired Implementation (Synthesized by Repair Agent)
   * 1. Fine-grained mutex lock per sender to prevent concurrency races.
   * 2. Atomic state machine: Verified -> Held -> Transferred.
   * 3. Full rollback handling if failure occurs during processing.
   * 4. Strict idempotency key store to neutralize retry storms.
   * 5. Invariant validation ensuring 0 money creation/destruction.
   */
  private async executePatchedTransfer(req: TransferRequest, systemMoneyBefore: number): Promise<TransferResult> {
    const releaseSenderLock = await this.acquireLock(req.senderId);
    let releaseRecipientLock: (() => void) | null = null;

    try {
      releaseRecipientLock = await this.acquireLock(req.recipientId);

      const sender = this.users.get(req.senderId);
      const recipient = this.users.get(req.recipientId);

      if (!sender || !recipient) {
        return {
          success: false,
          error: 'WALLET_NOT_FOUND',
          systemMoneyBefore,
          systemMoneyAfter: this.getTotalSystemMoney(),
        };
      }

      // Strict balance check with zero race condition tolerance
      if (sender.balancePaise < req.amountPaise) {
        const rejectedTx: TransactionRecord = {
          id: `tx_rep_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
          idempotencyKey: req.idempotencyKey,
          senderId: sender.id,
          senderName: sender.name,
          recipientId: recipient.id,
          recipientName: recipient.name,
          amountPaise: req.amountPaise,
          status: 'REJECTED_INSUFFICIENT_FUNDS',
          timestamp: new Date().toISOString(),
          systemMoneyChecksumBefore: systemMoneyBefore,
          systemMoneyChecksumAfter: this.getTotalSystemMoney(),
          enginePhase: 'repaired',
          reasonNote: 'Rejected: Insufficient verified funds in atomic lock.',
        };
        this.ledger.unshift(rejectedTx);
        this.idempotencyStore.set(req.idempotencyKey, rejectedTx);
        return {
          success: false,
          transaction: rejectedTx,
          error: `INSUFFICIENT_FUNDS: Current balance ₹${(sender.balancePaise / 100).toFixed(2)} is less than required ₹${(req.amountPaise / 100).toFixed(2)}`,
          systemMoneyBefore,
          systemMoneyAfter: this.getTotalSystemMoney(),
        };
      }

      // Simulated atomic transaction checkpoint
      const senderSnapshot = sender.balancePaise;
      const recipientSnapshot = recipient.balancePaise;

      try {
        // Execute debit
        sender.balancePaise -= req.amountPaise;

        // Simulate network / DB fault test if requested
        if (req.simulateMidTxFailure) {
          throw new Error('SIMULATED_DATABASE_IO_ABORT: Transaction interrupted before credit');
        }

        // Execute credit
        recipient.balancePaise += req.amountPaise;

        // Invariant audit: Money conservation guarantee
        const systemMoneyAfter = this.getTotalSystemMoney();
        if (systemMoneyAfter !== systemMoneyBefore) {
          // Emergency rollback
          sender.balancePaise = senderSnapshot;
          recipient.balancePaise = recipientSnapshot;
          throw new Error(`INVARIANT_VIOLATION: System money altered from ${systemMoneyBefore} to ${systemMoneyAfter}! Auto-rolled back.`);
        }

        const committedTx: TransactionRecord = {
          id: `tx_rep_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
          idempotencyKey: req.idempotencyKey,
          senderId: sender.id,
          senderName: sender.name,
          recipientId: recipient.id,
          recipientName: recipient.name,
          amountPaise: req.amountPaise,
          status: 'COMMITTED',
          timestamp: new Date().toISOString(),
          systemMoneyChecksumBefore: systemMoneyBefore,
          systemMoneyChecksumAfter: systemMoneyAfter,
          enginePhase: 'repaired',
          reasonNote: 'Atomic two-phase commit verified. Money conserved.',
        };

        this.ledger.unshift(committedTx);
        this.idempotencyStore.set(req.idempotencyKey, committedTx);

        return {
          success: true,
          transaction: committedTx,
          systemMoneyBefore,
          systemMoneyAfter,
        };
      } catch (innerError: any) {
        // Atomic Rollback
        sender.balancePaise = senderSnapshot;
        recipient.balancePaise = recipientSnapshot;

        const rolledBackTx: TransactionRecord = {
          id: `tx_rep_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
          idempotencyKey: req.idempotencyKey,
          senderId: sender.id,
          senderName: sender.name,
          recipientId: recipient.id,
          recipientName: recipient.name,
          amountPaise: req.amountPaise,
          status: 'ROLLED_BACK',
          timestamp: new Date().toISOString(),
          systemMoneyChecksumBefore: systemMoneyBefore,
          systemMoneyChecksumAfter: this.getTotalSystemMoney(),
          enginePhase: 'repaired',
          reasonNote: `ATOMIC_ROLLBACK_SUCCESSFUL: ${innerError.message}. Balances restored cleanly.`,
        };

        this.ledger.unshift(rolledBackTx);
        this.idempotencyStore.set(req.idempotencyKey, rolledBackTx);

        return {
          success: false,
          transaction: rolledBackTx,
          error: `TRANSACTION_ROLLED_BACK: ${innerError.message}`,
          systemMoneyBefore,
          systemMoneyAfter: this.getTotalSystemMoney(),
        };
      }
    } finally {
      if (releaseRecipientLock) releaseRecipientLock();
      releaseSenderLock();
    }
  }
}

// Global Singleton for application runtime
export const globalWalletEngine = new WalletEngine();
